#!/usr/bin/env bash

###################################################################
#
#   Install tox requirements.
#
#   This file is managed by tox, no need to run it manually.
##################################################################

set -e

if test -e "${OPENEDX_RELEASE}"; then
  echo "The OPENEDX_RELEASE environment variable is not set, please only run this script via '$ tox'.";
fi

cd "${TOX_INI_DIR}"

# Step 1: Download the Open edX release requirements/edx/development.txt file
DEV_REQUIREMENTS_URL="https://github.com/edx/edx-platform/raw/open-release/${OPENEDX_RELEASE}.master/requirements/edx/development.txt"
DEV_REQUIREMENTS_FILE="requirements/${OPENEDX_RELEASE}-development.txt"
TOX_REQUIREMENTS_FILE="requirements/${OPENEDX_RELEASE}-tox.txt"

curl -L "${DEV_REQUIREMENTS_URL}" --output "${DEV_REQUIREMENTS_FILE}"

# Step 2: Initialize the tox requirements file
echo "#
# Warning: Do not edit this file directly, it is managed by '$ tox'
#          Run the '$ tox -e build-release-requirements' to create a
#          release requirements file.
#

" > "${TOX_REQUIREMENTS_FILE}"

# Step 3: Download only needed packages
grep -i \
  -e 'django==' \
  -e 'babel==' \
  -e 'edx-i18n-tools==' \
  -e 'django-babel==' \
  -e 'django-babel-underscore==' \
  -e 'mako==' \
  -e 'polib==' -- "${DEV_REQUIREMENTS_FILE}" >> "${TOX_REQUIREMENTS_FILE}"
