name: Sync prod with main
on:
  push:
    branches:
      - juniper/main
jobs:
  auto-pull-request:
    name: PullRequestAction
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_PREFIX: "juniper/main"
          PULL_REQUEST_BRANCH: "juniper/prod"
          PULL_REQUEST_TITLE: "Update from `juniper/main` (production)"
          PULL_REQUEST_BODY: |
            This is an automated pull request to update `juniper/prod` with changes from `juniper/main`.
            Please review the changes to make sure they're production ready.
